# supports both uv and poetry instllations
[project]
name = "sample"
version = "0.1.1-202410"
description = "Rich's Python Project for both UV and Poetry"
readme = "README.md"
# this is too broad 3.13 as of 10-24 is not supported by tensorflow
# open-webui only works with 3.11 as or 10-24
# requires-python = "==3.11.*"
requires-python = "<=3.12"
dependencies = []

[tool.uv]
dev-dependencies = [
  # "fontawesome-markdown>=0.2.6",  # deprecated to pipx install
  # "mkdocs>=1.6.1",
  # "mkdocs-material>=9.5.38",
  # "mkdocstrings[python]>=0.26.1",
  "neovim>=0.3.1",
]

[tool.poetry]
# note that the name must *not* be an existing pip package
name = "sample"
version = "0.1.0"
description = "Rich's Poetry installation"
authors = ["Rich Tong <1782087+richtong@users.noreply.github.com>"]
readme = "README.md"
package-mode = false

# most of these dependencies are now in brew or pipx install
[tool.poetry.dependencies]
python = "^3.11.1"
# black = ">=22.12"
# bandit = "^1.7.4"
# beautysh = "^6.2.1"
# build = "^0.10.0" # move to hatch
# flake8 = "^6.0.0"  # deprecated for ruff
# fontawesome-markdown = "^0.2.6"
# isort = ">=5.10.1"  # deprecated for ruff
# mkdocs = "^1.4.2"  # pipx
# mkdocs-material = "^9.0.11"  # pipx
# mypy = "^1.0.0" ## pipx
neovim = "^0.3.1"
# pdoc3 = "^0.10.0"  # moving to mkdcos
# pre-commit = "^3.0.4"  # brew
# pydocstyle = "^6.3.0"  # deprecated
# pymdown-extensions = "^10.0.0" # pipx mkdocs
# seed-isort-config = "^2.2.0"
# setuptools = "^70.0.0"  # moving to hatch
# twine = "^4.0.2"  # moving to hatch
# wheel = "^0.38.4"  # moving hatch
# yamllint = "^1.29.0"  # brew

# poetry build system but switching to uv or hatchling
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# https://docs.astral.sh/ruff/configuration/
[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".ipynb_checkpoints",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pyenv",
  ".pytest_cache",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  ".vscode",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "site-packages",
  "venv",
]

# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.11
target-version = "py311"

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or

# Richt's aggressive defaults are:
# "F", -- pyright
# "E", -- pycodestyle
# "W", -- pycodestyle warnings
# "C", -- mccabe code complexity
# "I", -- isort
# "N", -- PEP8 naming
# "N", -- PEP8 naming
# "D", -- pydocstyle docstrings
# "UP", -- pyupgrade
# "YTT", -- flake8-2020
# "ANN", -- flake8-annotations
# "S", -- flake8-bandit
# "FBT", -- flake8-boolean-trap
# "B", -- flake8-bugbear
# "A", -- flake8-builtin showing
# "COM", -- flake8-commas missing
# "C4", -- flake8-comprehensions simplification
# "DTZ", -- flake8-datetimez errors
# "EM", -- flake8-errmsg
# "EXE", -- flake8-executalbe
# "PTH", -- flake8-use-pathlib no os.path
# "PD", -- pandas-vet
# "PL", -- pylint refactor, warn, errors
# "NPY", -- numpy
# "PERF", -- perflint
# "DOC", -- pydoclint
# "RUF", -- ruff specific rules
select = [
  "F",
  "E",
  "W",
  "C",
  "I",
  "N",
  "N",
  "D",
  "UP",
  "YTT",
  "ANN",
  "S",
  "FBT",
  "B",
  "A",
  "COM",
  "C4",
  "DTZ",
  "EM",
  "EXE",
  "PTH",
  "PD",
  "PL",
  "NPY",
  "PERF",
  "DOC",
  "RUF",
]
# ignor conflicting rules
ignore = [
  "D203", # no blank lines before docstring in class (Google convention)
  "D213", # one line after summary (Google convention)
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = true

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"
